
###
POST {{openaiBaseUrl}}/openai/deployments/{{openaiDeploymentId}}/chat/completions?api-version={{openaiApiVersion}}  HTTP/1.1
 Content-Type: application/json
 api-key: {{openaiApiKey}}  

{
    "messages": [
        {
      "role": "system",
      "content": "You are an AI assistant that helps users find information."
        },
        {
            "role": "user",
            "content": "which is the capital of Australia?"
        }
    ]
}
### simple completion
curl -i -X POST {{openaiBaseUrl}}/openai/deployments/{{openaiDeploymentId}}/chat/completions?api-version={{openaiApiVersion}} \
-H "Content-Type: application/json" \
-H "api-key: {{openaiApiKey}}" \
-d \
'
{
    "messages": [
        {
            "role": "user",
            "content": "Quel ramo del lago di Como, che volge a mezzogiorno"
        }
    ]
}
'
### completion ask to answer in json format
curl -i -X POST {{openaiBaseUrl}}/openai/deployments/{{openaiDeploymentId}}/chat/completions?api-version={{openaiApiVersion}} \
-H "Content-Type: application/json" \
-H "api-key: {{openaiApiKey}}" \
-d \
'
{
    "messages": [
        {
      "role": "system",
      "content": "You are an AI assistant that to transform the text in json. use the following format fields: name, surname, age, city, phone number"
        },
        {
            "role": "user",
            "content": "Hi I am John Doe, 25 years old, from New York, my phone number is 123456789"
        }
    ]
}
'